train_file: '/temp/vl-dataset/json_downstream/ve/ve_train.json'
val_file: '/temp/vl-dataset/json_downstream/ve/ve_dev.json'
test_file: '/temp/vl-dataset/json_downstream/ve/ve_test.json'

image_root: '/temp/vl-dataset/common-images/flickr30k/flickr30k-images/'

image_res: 384
batch_size_train: 16 # 32
batch_size_test: 32 # 64

alpha: 0.4
distill: True
warm_up: False

bert_config: 'configs/config_bert.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 500, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 1, cooldown_epochs: 0}







